from abc import ABC, abstractmethod

class StateRepository(ABC):
    @abstractmethod
    def add_transaction(self, transaction): ...
    @abstractmethod
    def add_alert(self, alert): ...
    @abstractmethod
    def add_account(self, account): ...
    @abstractmethod
    def snapshot(self): ...
